In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Embedding, LSTM, Dense, Input
from tensorflow.keras.models import Sequential, Model

In [2]:
df=pd.read_csv("engTamilTrain.csv")
df=df.drop(["Unnamed: 0"], axis=1)

In [3]:
df

en  \
0       MMA vice president Qazi Hussain Ahmad declared...   
1       Information has surfaced in recent years sugge...   
2       And Azor begat Sadoc; and Sadoc begat Achim; a...   
3       She says she knows what is going on, but can d...   
4       And be it indeed that I have erred, my error r...   
...                                                   ...   
166866  Soon to be released, 'Silandhi' is produced by...   
166867   An MHP deputy publicly stated, "Let them die."\n   
166868  And Aaron shall make an atonement on the horns...   
166869  Like the CWC, the UPF is part of the governmen...   
166870  If I had been, the split would not have happen...   

                                                       ta  
0       MMA கட்சியின் துணைத்தலைவர் க்வாஸி ஹுசேன் அகமத்...  
1       சமீபகாலத்தில் சில தகவல்கள் யூலியஸ் ரோசன்பேர்க...  
2       ஆசோர் சாதோக்கைப் பெற்றான்; சாதோக்கு ஆகீமைப் பெ...  
3       என்ன நடக்கிறது என்பது தமக்கு தெரியும் என்றும் ...  
4       நான் தப்பிநடந்தது மெய்யானாலும், என் தப்பிதம் எ...  
...                                                   ...  
166866  விரைவில் திரைக்கு வர இருக்கும் 'சிலந்தி' படத்த...  
166867  தேசியவாத இயக்கங்களின் கட்சி (MHP) யின் உபதலைவர...  
166868  வருஷத்தில் ஒருமுறை ஆரோன் பாவநிவாரணபலியின் இரத்...  
166869  இ.தொ.கா. போலவே, மலையக மக்கள் முன்னணியும் அரச...  
166870  அந்த சமயம் மட்டும் நான் இங்கே இருந்திருந்தா அந...  

[166871 rows x 2 columns]

In [4]:
english_sentences=df["en"]
tamil_sentences=df["ta"]
english_sentences=english_sentences.head(1000)
tamil_sentences=tamil_sentences.head(1000)

In [5]:
def addSosEos (seriesSentences):
    sos_token = "<SOS>"
    eos_token = "<EOS>"
    statements_with_token = [f"{sos_token} {statement} {eos_token}" for statement in seriesSentences]
    english_Sent=[]
    for statements in statements_with_token:
        english_Sent.append(statements)
        print(statements)
    return english_Sent

In [6]:
english_sent_SE=addSosEos(english_sentences)
tamil_sent_SE=addSosEos(tamil_sentences)

<SOS> MMA vice president Qazi Hussain Ahmad declared last month: 'We are not extremists.
 <EOS>
<SOS> Information has surfaced in recent years suggesting that Julius Rosenberg was involved in passing some form of intelligence to Soviet officials during the Second World War.
 <EOS>
<SOS> And Azor begat Sadoc; and Sadoc begat Achim; and Achim begat Eliud;
 <EOS>
<SOS> She says she knows what is going on, but can do nothing about it.
 <EOS>
<SOS> And be it indeed that I have erred, my error remains with myself.
 <EOS>
<SOS> Finally, the columnist fails to tell us who among the political leaders of the bourgeoisie, past and present, he counts among the paragons of morality.
 <EOS>
<SOS> These include the British Tamil Forum, La Maison du Tamil Eelam (France), the Canadian Tamil Congress, and the Swiss Tamil Forum.
 <EOS>
<SOS> Vijay accompanied with his wife and daughter enjoyed the film 'Anjathey'.
 <EOS>
<SOS> Both Musharraf and Vajpayee have exploited the current war drive to divert pub

In [7]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

## Tokenize

In [8]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
eng_tokenizer=Tokenizer(filters="")
eng_tokenizer.fit_on_texts(english_sent_SE)
eng_vocab_size=len(eng_tokenizer.word_index) + 1
eng_sequences=eng_tokenizer.texts_to_sequences(english_sent_SE)

In [9]:
eng_tokenizer

In [10]:
eng_vocab_size

6979

In [11]:
print(eng_sequences)

[[2, 2036, 2037, 224, 2038, 1113, 2039, 285, 57, 2040, 445, 24, 23, 2041, 3], [2, 762, 18, 2042, 7, 567, 143, 2043, 9, 2044, 2045, 15, 568, 7, 2046, 126, 1114, 4, 340, 6, 446, 447, 184, 1, 341, 105, 342, 3], [2, 5, 2047, 448, 2048, 5, 2049, 448, 2050, 5, 2051, 448, 2052, 3], [2, 86, 449, 86, 343, 106, 10, 344, 1115, 37, 91, 127, 450, 79, 225, 3], [2, 5, 20, 19, 451, 9, 33, 22, 2053, 59, 2054, 763, 17, 2055, 3], [2, 1116, 1, 1117, 2056, 6, 569, 35, 41, 172, 1, 67, 452, 4, 1, 1118, 226, 5, 1119, 16, 2057, 172, 1, 2058, 4, 2059, 3], [2, 53, 764, 1, 345, 92, 2060, 2061, 2062, 1120, 92, 765, 2063, 1, 2064, 92, 2065, 5, 1, 2066, 92, 1121, 3], [2, 766, 2067, 17, 21, 1122, 5, 453, 1123, 1, 78, 2068, 3], [2, 95, 767, 5, 1124, 22, 768, 1, 346, 49, 2069, 6, 2070, 128, 769, 26, 34, 2071, 25, 570, 5, 6, 770, 58, 34, 1125, 2072, 3], [2, 37, 106, 2073, 3], [2, 2074, 2075, 6, 35, 79, 771, 5, 32, 24, 772, 19, 46, 64, 2076, 60, 8, 2077, 2078, 773, 7, 2079, 41, 774, 70, 2080, 4, 2081, 7, 1, 771, 342, 3],

In [12]:
tam_tokenizer=Tokenizer(filters="")
tam_tokenizer.fit_on_texts(tamil_sent_SE)
tam_vocab_size=len(tam_tokenizer.word_index) + 1
tam_sequences=tam_tokenizer.texts_to_sequences(tamil_sent_SE)

In [13]:
tam_tokenizer

In [14]:
tam_vocab_size

9922

In [15]:
print(tam_sequences)

[[1, 1836, 44, 1837, 1838, 1839, 1840, 148, 78, 884, 1841, 1842, 885, 282, 2], [1, 1843, 69, 886, 1844, 1845, 3, 1846, 1847, 283, 551, 1848, 1849, 1850, 1851, 1852, 1853, 2], [1, 1854, 1855, 887, 1856, 1857, 887, 1858, 1859, 1860, 2], [1, 284, 1861, 33, 888, 1862, 35, 149, 1863, 382, 1864, 35, 552, 889, 2], [1, 11, 1865, 1866, 17, 1867, 1868, 1869, 2], [1, 1870, 1871, 1872, 1873, 1874, 553, 1875, 2], [1, 6, 1876, 1877, 383, 1878, 1879, 1880, 1881, 383, 1882, 1883, 233, 1884, 383, 1885, 1886, 383, 1887, 1888, 384, 890, 2], [1, 26, 1889, 1890, 1891, 111, 1892, 1893, 2], [1, 1894, 4, 1895, 1896, 554, 150, 891, 385, 91, 285, 1897, 1898, 554, 1899, 1900, 1901, 1902, 286, 555, 1903, 892, 2], [1, 36, 284, 1904, 2], [1, 1905, 234, 19, 893, 1906, 127, 92, 894, 556, 1907, 5, 1908, 12, 3, 895, 287, 1909, 896, 79, 2], [1, 80, 1910, 1911, 112, 1912, 1913, 112, 1914, 1915, 1916, 1917, 1918, 1919, 128, 1920, 1921, 17, 1922, 6, 897, 898, 129, 1923, 5, 1924, 2], [1, 1925, 899, 1926, 1927, 1928, 70, 192

In [16]:
max_input_seq_length=20
max_output_seq_length=20

## pad sequences

In [17]:
input_sequence=pad_sequences(eng_sequences, maxlen=max_input_seq_length, padding='post')
output_sequence=pad_sequences(tam_sequences, maxlen=max_output_seq_length, padding='post')

In [18]:
output_sequence

array([[   1, 1836,   44, ...,    0,    0,    0],
       [   1, 1843,   69, ...,    2,    0,    0],
       [   1, 1854, 1855, ...,    0,    0,    0],
       ...,
       [9890, 9891,   86, ..., 9899, 9900,    2],
       [9904, 9905, 9906, ..., 1036, 9919,    2],
       [   1,  195,   25, ...,    0,    0,    0]])

## Prepare decoder sequences for teacher forcing

In [21]:
decoder_input_sequences=np.zeros_like(output_sequence)  #all values will be change 0
decoder_input_sequences[:, 1:] = output_sequence[:, :-1] # entire row and columns except last columns 
decoder_input_sequences[:, 0] = tam_tokenizer.word_index['<sos>'] 
decoder_output_sequences = np.eye(tam_vocab_size)[output_sequence]   #one hot encoding

In [22]:
np.zeros_like(output_sequence)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
decoder_input_sequences[:, 1:]

array([[   1, 1836,   44, ...,    0,    0,    0],
       [   1, 1843,   69, ..., 1853,    2,    0],
       [   1, 1854, 1855, ...,    0,    0,    0],
       ...,
       [9890, 9891,   86, ...,    3, 9899, 9900],
       [9904, 9905, 9906, ...,  232, 1036, 9919],
       [   1,  195,   25, ...,    0,    0,    0]])

In [24]:
tam_tokenizer.word_index

{'<sos>': 1,
 '<eos>': 2,
 'ஒரு': 3,
 'மற்றும்': 4,
 'என்று': 5,
 'இந்த': 6,
 'அவர்': 7,
 'அமெரிக்க': 8,
 'என்ற': 9,
 'என': 10,
 'நான்': 11,
 'உள்ள': 12,
 'அரசியல்': 13,
 'இருந்து': 14,
 'அந்த': 15,
 'அது': 16,
 'என்': 17,
 'கட்சி': 18,
 'அவர்கள்': 19,
 'மக்கள்': 20,
 'பல': 21,
 'அதன்': 22,
 'பற்றி': 23,
 'புஷ்': 24,
 'எதிராக': 25,
 'தனது': 26,
 'இரண்டு': 27,
 'அரசாங்கம்': 28,
 'அவன்': 29,
 'கடந்த': 30,
 'இது': 31,
 'பெரும்': 32,
 'என்பது': 33,
 'போர்': 34,
 'என்றும்': 35,
 'ஆனால்': 36,
 'மேலும்': 37,
 'வேண்டும்': 38,
 'ஈராக்': 39,
 'இருந்த': 40,
 'சமூக': 41,
 'புதிய': 42,
 'ஐரோப்பிய': 43,
 'கட்சியின்': 44,
 'ஆண்டு': 45,
 'சர்வதேச': 46,
 'மீது': 47,
 'இருக்கும்': 48,
 'அல்லது': 49,
 'பெரிய': 50,
 'நிர்வாகம்': 51,
 'பொருளாதார': 52,
 'ஜனநாயக': 53,
 'சோசலிச': 54,
 'தொழிலாள': 55,
 'என்பதை': 56,
 'உள்ளது.\n': 57,
 'இரு': 58,
 'மூலம்': 59,
 'பற்றிய': 60,
 'பின்னர்': 61,
 'அதை': 62,
 'இராணுவ': 63,
 'தன்': 64,
 'மில்லியன்': 65,
 'எந்த': 66,
 'தமது': 67,
 '-': 68,
 'சில': 69,
 'முக்கிய': 7

In [25]:
decoder_input_sequences[:, 0] 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [28]:
decoder_output_sequences 

array([[[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 1., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0.

In [27]:
from gensim.models import Word2Vec
eng_model=Word2Vec.load("engmodel.bin")
tam_model=Word2Vec.load("tammodel.bin")

In [27]:
print(eng_model)

Word2Vec<vocab=7300, vector_size=100, alpha=0.025>


In [29]:
def create_embedding_matrix(word2vec_model, tokenizer, vocab_size):
    embedding_matrix=np.zeros((vocab_size, word2vec_model.vector_size))
    for word, i in tokenizer.word_index.items():
        try:
            embedding_vector = word2vec_model.wv[word]
            embedding_matrix[i]=embedding_vector
        except KeyError:
            pass  #  words not found in the embedding index will be all zeros
    return embedding_matrix

In [30]:
eng_embedding_matrix = create_embedding_matrix(eng_model, eng_tokenizer, eng_vocab_size)
tam_embedding_matrix = create_embedding_matrix(tam_model, tam_tokenizer, tam_vocab_size)

In [31]:
embedding_matrix=np.zeros((eng_vocab_size, eng_model.vector_size))
embedding_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]:
for word, i in eng_tokenizer.word_index.items():
    try:
        embedding_vector = eng_model.wv[word]
        embedding_matrix[i]=embedding_vector
    except KeyError:
        pass

In [32]:
eng_embedding_matrix.shape

(6979, 100)

In [33]:
tam_embedding_matrix.shape

(9922, 100)

In [34]:
def create_seq2seq_model(input_vocab_size, output_vocab_size, input_seq_length, output_seq_length, hidden_units, eng_embedding_matrix, tam_embedding_matrix): 
        # Encoder
    encoder_inputs=Input(shape=(input_seq_length,))
    encoder_embedding = Embedding(input_vocab_size, hidden_units, weights=[eng_embedding_matrix], trainable=False)(encoder_inputs)
    encoder_lstm, encoder_state_h, encoder_state_c = LSTM(hidden_units, return_state=True)(encoder_embedding)
    # Decoder
    decoder_inputs = Input(shape=(output_seq_length,))
    decoder_embedding = Embedding(output_vocab_size, hidden_units, weights=[tam_embedding_matrix], trainable=False)(decoder_inputs)
    decoder_lstm = LSTM(hidden_units, return_sequences=True, return_state=True)
    decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=[encoder_state_h, encoder_state_c])
    decoder_dense = Dense(output_vocab_size, activation='softmax')
    decoder_outputs = decoder_dense(decoder_outputs)

    model = Model([encoder_inputs, decoder_inputs], decoder_outputs)
    return model


## Encoder

In [72]:
encoder_inputs=Input(shape=(max_input_seq_length,))
encoder_embedding = Embedding(eng_vocab_size, 100, weights=[eng_embedding_matrix], trainable=False)(encoder_inputs)
encoder_lstm, encoder_state_h, encoder_state_c = LSTM(100, return_state=True)(encoder_embedding)
print(encoder_lstm)
print(encoder_state_h)
print(encoder_state_c)

<KerasTensor shape=(None, 100), dtype=float32, sparse=False, ragged=False, name=keras_tensor_60>
<KerasTensor shape=(None, 100), dtype=float32, sparse=False, ragged=False, name=keras_tensor_61>
<KerasTensor shape=(None, 100), dtype=float32, sparse=False, ragged=False, name=keras_tensor_62>


## Decoder

In [59]:
decoder_inputs = Input(shape=(max_output_seq_length,))
decoder_embedding = Embedding(tam_vocab_size, 100, weights=[tam_embedding_matrix], trainable=False)(decoder_inputs)
decoder_lstm = LSTM(100, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=[encoder_state_h, encoder_state_c])
decoder_dense = Dense(tam_vocab_size, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

In [73]:
print(decoder_embedding)
print(decoder_lstm)
print(decoder_outputs)
print(decoder_dense)
print(decoder_outputs)

<KerasTensor shape=(None, 20, 100), dtype=float32, sparse=False, ragged=False, name=keras_tensor_50>
<LSTM name=lstm_10, built=True>
<KerasTensor shape=(None, 20, 9922), dtype=float32, sparse=False, ragged=False, name=keras_tensor_54>
<Dense name=dense_3, built=True>
<KerasTensor shape=(None, 20, 9922), dtype=float32, sparse=False, ragged=False, name=keras_tensor_54>


In [74]:
target_sequences = tf.keras.utils.to_categorical(output_sequence, num_classes=tam_vocab_size)

In [75]:
target_sequences

array([[[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 1., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0.

In [76]:
model = create_seq2seq_model(eng_vocab_size, tam_vocab_size, max_input_seq_length, max_output_seq_length, 100, eng_embedding_matrix, tam_embedding_matrix)

In [77]:
model

<Functional name=functional_2, built=True>

In [78]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [79]:
batch_size = 32
epochs = 500
model.fit([input_sequence, output_sequence], decoder_output_sequences, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 15s 361ms/step - accuracy: 0.2257 - loss: 9.0911 - val_accuracy: 0.2722 - val_loss: 8.2059
Epoch 2/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 7s 277ms/step - accuracy: 0.2580 - loss: 7.5966 - val_accuracy: 0.2697 - val_loss: 7.4766
Epoch 3/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 6s 243ms/step - accuracy: 0.2916 - loss: 6.4263 - val_accuracy: 0.2722 - val_loss: 7.5110
Epoch 4/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 6s 251ms/step - accuracy: 0.2607 - loss: 6.5049 - val_accuracy: 0.2722 - val_loss: 7.5584
Epoch 5/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 7s 247ms/step - accuracy: 0.2779 - loss: 6.2761 - val_accuracy: 0.2718 - val_loss: 7.5313
Epoch 6/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 6s 243ms/step - accuracy: 0.2565 - loss: 6.3603 - val_accuracy: 0.2720 - val_loss: 7.5178
Epoch 7/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 6s 240ms/step - accuracy: 0.2717 - loss: 6.1978 - val_accuracy: 0.2720 - val_loss: 7.5114
Epoch 8/500
25/25 ━━━━━━━━━━━━━━━━━━━━ 6s 256ms/step - accuracy: 0.2567 - loss: 6.2882 - val_acc

In [80]:
# Preprocessing the input
input_sentence = "<sos>Finally, the columnist fails to tell us who among the political leaders of the bourgeoisie, past and present, he counts among the paragons of morality<eos>"

# Convert the input sentence to sequence
input_sequence = eng_tokenizer.texts_to_sequences([input_sentence])

# Pad the statement to the maximum input sequence length
input_sequence = pad_sequences(input_sequence, maxlen=max_input_seq_length, padding='post')

# Generate predictions
predictions = model.predict([input_sequence, np.zeros((1, max_output_seq_length))])

# Convert predictions to tokens
predicted_tokens = np.argmax(predictions, axis=-1)[0]

# Create index to word mapping for Tamil vocabulary
tamil_index_word = {i: w for w, i in tam_tokenizer.word_index.items()}


# Convert tokens to text
decoded_sentence = []
for token in predicted_tokens:
    if token == 0:  # Assuming 0 is the padding token
        continue
    word = tamil_index_word.get(token)
    if word == '<eos>':
        break
    if word is not None:
        decoded_sentence.append(word)
    else:
        decoded_sentence.append('<unk>')

# Join the words to form the decoded statement
decoded_statement = ' '.join(decoded_sentence)

# Print the decoded statement
print(decoded_statement)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 865ms/step
ராஜாவாகி, உங்களுக்கு உங்களுக்கு இருப்பினும், பரந்த அளவிலான அங்கே அங்கே அங்கே அங்கே வன்முறையினை கர்த்தராகிய இருக்கிறார் உறையச்செய்யும் அப்பாஸ் நிரூபிக்கவில்லை" என்றார்.



In [81]:
input_sequence

array([[   6,  569,   35,   41,  172,    1,   67,  452,    4,    1, 1118,
         226,    5, 1119,   16, 2057,  172,    1, 2058,    4]])

In [82]:
predictions

array([[[4.4257063e-06, 4.4814835e-04, 6.5573244e-07, ...,
         1.9555113e-10, 2.6180760e-10, 2.1813806e-10],
        [3.3283020e-06, 4.4913636e-06, 4.1124977e-07, ...,
         9.5968733e-10, 1.1538038e-09, 1.0267194e-09],
        [4.6836185e-06, 1.1950240e-06, 5.6560452e-08, ...,
         1.5219505e-09, 1.8200775e-09, 1.6912779e-09],
        ...,
        [5.9193320e-05, 2.1192716e-05, 2.8634684e-02, ...,
         5.4526517e-10, 6.3315359e-10, 4.9333004e-10],
        [2.3381070e-03, 4.0256327e-06, 1.2464427e-01, ...,
         1.7603632e-10, 2.0844274e-10, 1.7474937e-10],
        [8.4001683e-03, 6.6722230e-08, 9.8620516e-01, ...,
         8.6679573e-13, 1.0780659e-12, 8.8107072e-13]]], dtype=float32)

In [83]:
predicted_tokens

array([2312,  193,  193, 1553,  349,  819,  761,  761,  761,  761, 7654,
          0,    0,  912,  820, 7658, 1550, 5662,   97,    2], dtype=int64)

In [84]:
tamil_index_word

{1: '<sos>',
 2: '<eos>',
 3: 'ஒரு',
 4: 'மற்றும்',
 5: 'என்று',
 6: 'இந்த',
 7: 'அவர்',
 8: 'அமெரிக்க',
 9: 'என்ற',
 10: 'என',
 11: 'நான்',
 12: 'உள்ள',
 13: 'அரசியல்',
 14: 'இருந்து',
 15: 'அந்த',
 16: 'அது',
 17: 'என்',
 18: 'கட்சி',
 19: 'அவர்கள்',
 20: 'மக்கள்',
 21: 'பல',
 22: 'அதன்',
 23: 'பற்றி',
 24: 'புஷ்',
 25: 'எதிராக',
 26: 'தனது',
 27: 'இரண்டு',
 28: 'அரசாங்கம்',
 29: 'அவன்',
 30: 'கடந்த',
 31: 'இது',
 32: 'பெரும்',
 33: 'என்பது',
 34: 'போர்',
 35: 'என்றும்',
 36: 'ஆனால்',
 37: 'மேலும்',
 38: 'வேண்டும்',
 39: 'ஈராக்',
 40: 'இருந்த',
 41: 'சமூக',
 42: 'புதிய',
 43: 'ஐரோப்பிய',
 44: 'கட்சியின்',
 45: 'ஆண்டு',
 46: 'சர்வதேச',
 47: 'மீது',
 48: 'இருக்கும்',
 49: 'அல்லது',
 50: 'பெரிய',
 51: 'நிர்வாகம்',
 52: 'பொருளாதார',
 53: 'ஜனநாயக',
 54: 'சோசலிச',
 55: 'தொழிலாள',
 56: 'என்பதை',
 57: 'உள்ளது.\n',
 58: 'இரு',
 59: 'மூலம்',
 60: 'பற்றிய',
 61: 'பின்னர்',
 62: 'அதை',
 63: 'இராணுவ',
 64: 'தன்',
 65: 'மில்லியன்',
 66: 'எந்த',
 67: 'தமது',
 68: '-',
 69: 'சில',
 70: 'முக்கிய

In [85]:
decoded_sentence

['ராஜாவாகி,',
 'உங்களுக்கு',
 'உங்களுக்கு',
 'இருப்பினும்,',
 'பரந்த',
 'அளவிலான',
 'அங்கே',
 'அங்கே',
 'அங்கே',
 'அங்கே',
 'வன்முறையினை',
 'கர்த்தராகிய',
 'இருக்கிறார்',
 'உறையச்செய்யும்',
 'அப்பாஸ்',
 'நிரூபிக்கவில்லை"',
 'என்றார்.\n']